#Requires -Version 7.2
[CmdletBinding()]
param(
    [string]$SigningDirectory = (Join-Path $env:USERPROFILE '.valem-signing'),
    [string]$AndroidSdkDirectory = $env:ANDROID_HOME,
    [string]$OutputDirectory = (Join-Path $PSScriptRoot '..\artifacts\android')
)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$repoRoot = Split-Path -Parent $PSScriptRoot
$buildDirectory = Join-Path $repoRoot 'src\VALE.Mobile\bin\Release\net10.0-android'
$apk = Join-Path $buildDirectory 'com.berkanayk.vale-Signed.apk'
$aab = Join-Path $buildDirectory 'com.berkanayk.vale.aab'
$keystore = Join-Path $SigningDirectory 'VALEM-upload-key.jks'
$passwords = Join-Path $SigningDirectory 'signing-passwords.clixml'
$certificate = Join-Path $SigningDirectory 'upload-certificate.pem'
foreach ($path in @($apk, $aab, $keystore, $passwords, $certificate)) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { throw "Required local signing input missing: $path" }
}
if (-not $AndroidSdkDirectory) { throw 'Android SDK directory is required.' }
$buildTools = Get-ChildItem -LiteralPath (Join-Path $AndroidSdkDirectory 'build-tools') -Directory |
    Where-Object { $_.Name -match '^\d+\.\d+\.\d+$' } | Sort-Object { [version]$_.Name } -Descending | Select-Object -First 1
if (-not $buildTools) { throw 'Android build-tools missing.' }
New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null
$output = (Resolve-Path -LiteralPath $OutputDirectory).Path
$previousStore = $env:VALE_LOCAL_STORE_PASSWORD
$previousKey = $env:VALE_LOCAL_KEY_PASSWORD
$saved = $null
try {
    # Only the VALEM credentials generated by create-android-play-keystore.ps1.
    # DPAPI decrypts in memory; native tools receive env references, never password
    # arguments or plaintext password files. AAB is signed with jarsigner directly.
    $saved = Import-Clixml -LiteralPath $passwords
    $env:VALE_LOCAL_STORE_PASSWORD = [pscredential]::new('VALEM', $saved.StorePassword).GetNetworkCredential().Password
    $env:VALE_LOCAL_KEY_PASSWORD = [pscredential]::new('VALEM', $saved.KeyPassword).GetNetworkCredential().Password
    & (Join-Path $buildTools.FullName 'apksigner.bat') sign --ks $keystore --ks-key-alias $saved.Alias `
        --ks-pass env:VALE_LOCAL_STORE_PASSWORD --key-pass env:VALE_LOCAL_KEY_PASSWORD `
        --out (Join-Path $output 'VALE.apk') $apk
    if ($LASTEXITCODE -ne 0) { throw 'Local APK signing failed.' }
    & jarsigner -keystore $keystore -storepass:env VALE_LOCAL_STORE_PASSWORD -keypass:env VALE_LOCAL_KEY_PASSWORD `
        -sigalg SHA256withRSA -digestalg SHA-256 -signedjar (Join-Path $output 'VALE.aab') $aab $saved.Alias
    if ($LASTEXITCODE -ne 0) { throw 'Local AAB signing failed.' }
    Copy-Item -LiteralPath $certificate -Destination (Join-Path $output 'upload-certificate.pem') -Force
} finally {
    $env:VALE_LOCAL_STORE_PASSWORD = $previousStore
    $env:VALE_LOCAL_KEY_PASSWORD = $previousKey
    if ($saved) { $saved.StorePassword.Dispose(); $saved.KeyPassword.Dispose() }
}
& (Join-Path $PSScriptRoot 'verify-android-package.ps1') -PackageDirectory $output -AndroidSdkDirectory $AndroidSdkDirectory
